"""add session csrf hash and invitation rotation link

Revision ID: 14c616e7b68c
Revises: 34260d5be01a
Create Date: 2026-07-14 16:17:35.079916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "14c616e7b68c"
down_revision: str | None = "34260d5be01a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_sessions",
        sa.Column(
            "csrf_token_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            server_default="",
            nullable=False,
        ),
    )
    op.add_column(
        "invitations",
        sa.Column(
            "superseded_by",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "superseded_by")
    op.drop_column("auth_sessions", "csrf_token_hash")
    # ### end Alembic commands ###
