"""initial documented schema

Revision ID: 34260d5be01a
Revises:
Create Date: 2026-07-14 15:44:22.641403

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "34260d5be01a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_drafts",
        sa.Column(
            "id", mysql.CHAR(charset="ascii", collation="ascii_bin", length=36), nullable=False
        ),
        sa.Column(
            "creator_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "recipient_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("property_alias", sa.String(length=160), nullable=False),
        sa.Column("private_address", sa.Text(), nullable=True),
        sa.Column("terms_json", sa.JSON(), nullable=False),
        sa.Column(
            "terms_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "agreement_id_onchain",
            mysql.DECIMAL(unsigned=True, precision=65, scale=0),
            nullable=True,
        ),
        sa.Column(
            "creation_tx_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=True,
        ),
        sa.Column("creation_block_number", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agreement_drafts")),
        sa.UniqueConstraint("terms_hash", name=op.f("uq_agreement_drafts_terms_hash")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_agreement_drafts_creator_address"),
        "agreement_drafts",
        ["creator_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agreement_drafts_status"), "agreement_drafts", ["status"], unique=False
    )
    op.create_table(
        "agreement_index",
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "agreement_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False
        ),
        sa.Column(
            "creator_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "recipient_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "terms_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("status_cache", sa.String(length=32), nullable=False),
        sa.Column("last_synced_block", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "created_tx_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("created_at_chain", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint(
            "chain_id", "contract_address", "agreement_id", name=op.f("pk_agreement_index")
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_agreement_index_creator_address"),
        "agreement_index",
        ["creator_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agreement_index_recipient_address"),
        "agreement_index",
        ["recipient_address"],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "actor_wallet",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=True,
        ),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=180), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_audit_log_actor_wallet"), "audit_log", ["actor_wallet"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False)
    op.create_table(
        "auth_nonces",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "wallet_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "nonce_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("used_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_nonces")),
        sa.UniqueConstraint("nonce_hash", name=op.f("uq_auth_nonces_nonce_hash")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_auth_nonces_expires_at"), "auth_nonces", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_auth_nonces_wallet_address"), "auth_nonces", ["wallet_address"], unique=False
    )
    op.create_index(
        "ix_auth_nonces_wallet_expiry",
        "auth_nonces",
        ["wallet_address", "expires_at"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column(
            "id", mysql.CHAR(charset="ascii", collation="ascii_bin", length=36), nullable=False
        ),
        sa.Column(
            "wallet_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_wallet_address"), "auth_sessions", ["wallet_address"], unique=False
    )
    op.create_index(
        "ix_auth_sessions_wallet_expiry",
        "auth_sessions",
        ["wallet_address", "expires_at"],
        unique=False,
    )
    op.create_table(
        "chain_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "tx_hash", mysql.CHAR(charset="ascii", collation="ascii_bin", length=66), nullable=False
        ),
        sa.Column("log_index", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("block_number", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "block_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("event_name", sa.String(length=80), nullable=False),
        sa.Column(
            "agreement_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=True
        ),
        sa.Column("claim_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("block_timestamp", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chain_events")),
        sa.UniqueConstraint(
            "chain_id",
            "contract_address",
            "tx_hash",
            "log_index",
            name=op.f("uq_chain_events_chain_id_contract_address_tx_hash_log_index"),
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_chain_events_agreement_id"), "chain_events", ["agreement_id"], unique=False
    )
    op.create_index(
        op.f("ix_chain_events_block_number"), "chain_events", ["block_number"], unique=False
    )
    op.create_index(op.f("ix_chain_events_claim_id"), "chain_events", ["claim_id"], unique=False)
    op.create_index(
        op.f("ix_chain_events_event_name"), "chain_events", ["event_name"], unique=False
    )
    op.create_table(
        "chain_sync_state",
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("last_finalized_block", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("last_synced_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("chain_id", "contract_address", name=op.f("pk_chain_sync_state")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "claim_index",
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "agreement_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False
        ),
        sa.Column("claim_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False),
        sa.Column("claim_type", sa.String(length=16), nullable=False),
        sa.Column(
            "liable_tenant",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=True,
        ),
        sa.Column(
            "amount_wei", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False
        ),
        sa.Column(
            "reason_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column(
            "evidence_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("yes_votes", mysql.SMALLINT(unsigned=True), nullable=False),
        sa.Column("no_votes", mysql.SMALLINT(unsigned=True), nullable=False),
        sa.Column("status_cache", sa.String(length=16), nullable=False),
        sa.Column(
            "submitted_tx_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("submitted_block", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "resolved_tx_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=True,
        ),
        sa.Column("resolved_block", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("last_synced_block", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint(
            "chain_id", "contract_address", "agreement_id", "claim_id", name=op.f("pk_claim_index")
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "evidence_manifests",
        sa.Column(
            "id", mysql.CHAR(charset="ascii", collation="ascii_bin", length=36), nullable=False
        ),
        sa.Column(
            "owner_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column(
            "manifest_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column("total_size_bytes", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_manifests")),
        sa.UniqueConstraint("manifest_hash", name=op.f("uq_evidence_manifests_manifest_hash")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_evidence_manifests_owner_address"),
        "evidence_manifests",
        ["owner_address"],
        unique=False,
    )
    op.create_table(
        "invitations",
        sa.Column(
            "id", mysql.CHAR(charset="ascii", collation="ascii_bin", length=36), nullable=False
        ),
        sa.Column("agreement_key", sa.String(length=180), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "wallet_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("used_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_by",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_invitations_agreement_key"), "invitations", ["agreement_key"], unique=False
    )
    op.create_index("ix_invitations_expiry", "invitations", ["expires_at"], unique=False)
    op.create_table(
        "wallet_profiles",
        sa.Column(
            "address", mysql.CHAR(charset="ascii", collation="ascii_bin", length=42), nullable=False
        ),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("address", name=op.f("pk_wallet_profiles")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "agreement_draft_tenants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "draft_id",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column("tenant_index", sa.SmallInteger(), nullable=False),
        sa.Column(
            "wallet_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("display_label", sa.String(length=80), nullable=True),
        sa.Column(
            "required_amount_wei",
            mysql.DECIMAL(unsigned=True, precision=65, scale=0),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["agreement_drafts.id"],
            name=op.f("fk_agreement_draft_tenants_draft_id_agreement_drafts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agreement_draft_tenants")),
        sa.UniqueConstraint(
            "draft_id",
            "wallet_address",
            name=op.f("uq_agreement_draft_tenants_draft_id_wallet_address"),
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "agreement_metadata",
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "contract_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column(
            "agreement_id", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False
        ),
        sa.Column("property_alias", sa.String(length=160), nullable=False),
        sa.Column("private_address", sa.Text(), nullable=True),
        sa.Column("terms_json", sa.JSON(), nullable=False),
        sa.Column("is_shareable", sa.Boolean(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id", "contract_address", "agreement_id"],
            [
                "agreement_index.chain_id",
                "agreement_index.contract_address",
                "agreement_index.agreement_id",
            ],
            name=op.f("fk_agreement_metadata_chain_id_agreement_index"),
        ),
        sa.PrimaryKeyConstraint(
            "chain_id", "contract_address", "agreement_id", name=op.f("pk_agreement_metadata")
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "claim_drafts",
        sa.Column(
            "id", mysql.CHAR(charset="ascii", collation="ascii_bin", length=36), nullable=False
        ),
        sa.Column("agreement_key", sa.String(length=180), nullable=False),
        sa.Column(
            "recipient_address",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=False,
        ),
        sa.Column("claim_type", sa.String(length=16), nullable=False),
        sa.Column(
            "liable_tenant",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=42),
            nullable=True,
        ),
        sa.Column(
            "amount_wei", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=False
        ),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column(
            "reason_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column(
            "evidence_manifest_id",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column(
            "evidence_hash",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=66),
            nullable=False,
        ),
        sa.Column(
            "tx_hash", mysql.CHAR(charset="ascii", collation="ascii_bin", length=66), nullable=True
        ),
        sa.Column(
            "claim_id_onchain", mysql.DECIMAL(unsigned=True, precision=65, scale=0), nullable=True
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_manifest_id"],
            ["evidence_manifests.id"],
            name=op.f("fk_claim_drafts_evidence_manifest_id_evidence_manifests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_drafts")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_claim_drafts_agreement_key"), "claim_drafts", ["agreement_key"], unique=False
    )
    op.create_index(op.f("ix_claim_drafts_status"), "claim_drafts", ["status"], unique=False)
    op.create_table(
        "evidence_files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "manifest_id",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column(
            "sha256", mysql.CHAR(charset="ascii", collation="ascii_bin", length=64), nullable=False
        ),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("storage_relative_path", sa.String(length=500), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["evidence_manifests.id"],
            name=op.f("fk_evidence_files_manifest_id_evidence_manifests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_files")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_evidence_files_manifest_id"), "evidence_files", ["manifest_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_files_sha256"), "evidence_files", ["sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Hand-adjusted from the autogenerated version: tables are dropped in
    # reverse dependency order WITHOUT dropping their indexes first, because
    # MySQL refuses to drop an index that still backs a foreign key
    # (dropping a table drops its indexes anyway). Child tables go first.
    op.drop_table("agreement_draft_tenants")  # FK -> agreement_drafts
    op.drop_table("agreement_metadata")  # FK -> agreement_index
    op.drop_table("claim_drafts")  # FK -> evidence_manifests
    op.drop_table("evidence_files")  # FK -> evidence_manifests
    op.drop_table("agreement_drafts")
    op.drop_table("agreement_index")
    op.drop_table("evidence_manifests")
    op.drop_table("audit_log")
    op.drop_table("auth_nonces")
    op.drop_table("auth_sessions")
    op.drop_table("chain_events")
    op.drop_table("chain_sync_state")
    op.drop_table("claim_index")
    op.drop_table("invitations")
    op.drop_table("wallet_profiles")
